version: '3.8'

services:
  prestashop:
    image: citrustiara/presta-be-194660:latest
    ports:
      - "19466:80" 
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    environment:
      - DB_SERVER=10.40.71.115
      - DB_NAME=BE_194660
      - DB_USER=root
      - DB_PASSWD=student
      - PS_DOMAIN=172.20.83.101:19466
      - PS_ENABLE_SSL=0
    networks:
      - cluster_network

networks:
  cluster_network:
    driver: overlay
